services:
  server:
    image: node:20.18
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "yarn && yarn knex migrate:latest && yarn build && yarn start"
    env_file:
      - .env
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: SeCur3P@ssw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      POSTGRES_DB: portfolio
    volumes:
      - portfolio_data:/var/lib/postgresql/data

volumes:
  portfolio_data: