services:
  server:
    image: node:20.18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./entrypoint.sh
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: SeCur3P@ssw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - portfolio_data:/var/lib/postgresql/data

volumes:
  portfolio_data: